### ISSUE TITLE
content is longer than page 

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#10]
at present, i'm looking at instructions:  the content is longer than the page, introducing an unnecessary scrollbar

i have not totally investigated this yet;  i suspect the height of "main" is being calculated,  but is not compensating for the height of the navbar.  one way to resolve this is by setting `position=absolute` for the navbar, and adding padding to the other content so it's not hidden.

i don't know how to work with core any more so i can't quite build/test this

**Comment by npaton** [comment]
I am not sure what the scenario is. When you have an instruction step higher than the available space on the page, scrollbars appear? Would you have a screenshot to illustrate this? (maybe black out private parts of screenshot if there are some).

**Comment by amaatouq** [comment]
yes, @joshua-a-becker I think I am noticing something like this. So if there is one page where the scrollbars appear because of the length of the content, it remains for the other pages of the experiment (i.e., you can always scroll down even when it is not needed).

**Comment by joshua-a-becker** [comment]
this occurs for the default setup no customization

chrome Version 69.0.3497.100 (Official Build) (64-bit)

see scrollbar at [screenshot](https://i.imgur.com/KQKRoz1.png)

**Comment by npaton** [comment]
This will be fixed in the upcoming v0.0.8.

**Comment by npaton** [comment]
v0.0.8 published.
