### ISSUE TITLE
Multiple games assigned to player

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#11]
This relates to Issue #5 but specifically pertains to the multiple games created per player

everything else in issue #5 is expected behavior

Code to replicate this error & a datadump of an example can be found at:
https://github.com/joshua-a-becker/empirica-default

This contains
- an app made with `npx create-empirica-app` containing nothing custom except an instructions page that creates a timer to synchronize everyone's entry to the lobby by programmatically triggering 'onNext'.  this requires a manually created global_configs collection with an entry containing a document of the form {"name":"time_to_start","value","hh:mm"}.   it's currently set to  assume the time_to_start is set to Chicago time.
- a sample R script for throwing bots at the waiting page, which requires chromium drivers in linux to be installed & required R packages
- a datadump of a case where users were assigned to multiple games

**Comment by npaton** [comment]
Thank you for this, I will take a look at soon as I can.

**Comment by npaton** [comment]
I did take a quick look and something quite bad is happening, but in a clean way. 👺A single game lobby is initiating the creation of multiple identical games. That's obviously horrible. But at least it's in one place, it's some distributed issue where different players are dropped into various games. I don't really understand at the moment how it's possible, there's a barrier at the beginning of the game creation process that verifies for this. So I'll have to investigate further. I might not be able to beginning of this week, but hopefully towards the end of the week.

**Comment by npaton** [comment]
I couldn't quite figure this out yet, my apologies. You got the multiple assignment issue with this test app?

**Comment by amaatouq** [comment]
potentially this will be solved when we add the custom assignment #28 .. I'll close this issue for now.
