### ISSUE TITLE
Delete/Archive factor value

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/meteor-empirica-core#110]
If I am creating Factors in the `/admin/factors` interface, and I make a typo, I can archive the Factor and try again. However, if I make a mistake while entering a Factor Value, I have to either archive the whole Factor and recreate all of it's values, or I can export and edit the `.yaml`.

It would be nice to be able to just delete a Factor Value in the interface itself, possibly just as a little [x] in a third column of the values table.

**Comment by amaatouq** [comment]
I guess we should only archive the factor value because there might be running (or finished) games with these old factor values.
