### ISSUE TITLE
Hooks non functional since recent changes

### ISSUE THREAD

**Issue by LBrinkmann** [empiricaly/meteor-empirica-core#119]
## Expected Behavior
The callback provided to game hooks, such as `onStageStart` should be provided with `game, round, stage` as arguments.

## Current Behavior
Since recent changes in `server.js` 
https://github.com/empiricaly/meteor-empirica-core/blob/44d1bfcde9ef4151b12b63b908c51418aa13b844/server.js#L82
the callbacks are not provided with `game, round, stage`. Instead, they are provided with the hook name as a string, e.g. "onGameStart" and itself. 

## Possible Solution
Reverting back to
```
  onGameStart(func) {
    config.onGameStart = func;
  }
```
solved it for me. However that is bypassing the relevant checks in `safeCallback`.
The problem seems to be, that `arguments` here (
https://github.com/empiricaly/meteor-empirica-core/blob/44d1bfcde9ef4151b12b63b908c51418aa13b844/server.js#L29)
are the arguments of `safeCallback` and not the arguments of the actual callback function provided by the experimenter.

PS: We got great performance improvements with the last changes :-) We were able to run 40 games in parallel now with 80 rounds each. Thanks for the great work!

**Comment by npaton** [comment]
A fix for this should be released today. 👍 

> PS: We got great performance improvements with the last changes :-) We were able to run 40 games in parallel now with 80 rounds each. Thanks for the great work!

Very good to hear, thank you for the feedback!
