### ISSUE TITLE
bot `onStageTick` callback not being called

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/meteor-empirica-core#127]
It seems that the `onStageTick` callback in the bot definition isn't being triggered in my experiment. 

I'm not quite sure how to debug the call. Using the meteor debugger, I can't get a breakpoint to break in the `api/games/server/cron.js` `Cron.add(...)` function. However stages are timing out properly, and that seems to be controlled by the same function. Perhaps whatever executes the function isn't visible to the debugger, as it's called on the cron schedule? (forgive me for not really knowing the terminology here)

It had been working with this experiment, but I've recently updated meteor and empirica, and I just noticed the issue. Afraid I can't say for sure if it was an update that broke things, or if I did something to my code.

empirica @ https://github.com/empiricaly/meteor-empirica-core/commit/92903252bdda34ddd62aade459a580517dc87565,
meteor 1.10.2

**Comment by JamesPHoughton** [comment]
Actually, I can set a breakpoint, but I was trying to do so after 
```js
if (!bot.onStageTick) {
            return;
          }
```
and `bot.onStageTick()` is not a function. (That's a great reason for it not being called!)

`bot.toString()` returns "() => safeCallback("bot", func)".

but the `onStageTick` is in the scopes:
![image](https://user-images.githubusercontent.com/4304478/82062957-e0dd0d00-9698-11ea-9327-8f303469145f.png)

maybe something changed about how it's accessed. I'll look into whether safeCallback has any special requirements...

**Comment by JamesPHoughton** [comment]
I think there may be a mistake in applying safeCallback to the object that the `Empirica.bot` takes as a second argument. (as the second argument is not a function): https://github.com/empiricaly/meteor-empirica-core/commit/3e89595f8c12485deb41714aa81415f71f19e5cb#r39205050

**Comment by JamesPHoughton** [comment]
Created a PR (https://github.com/empiricaly/meteor-empirica-core/pull/128) to pass the bot object (not a function) straight through to `api/games/server/cron.js` ` Cron.add()`. This moves the syntax back to how it was prior to the above change. Not sure if you want to add some of the function of safeCallback to the functions that are part of the object.

**Comment by npaton** [comment]
Thank you for fixing that James! For now let's just revert, the bot API isn't used as much, so we will forgo the addition of the safeCallback for now, and see if it's an issue.

@hubertusputu1 Let's push out a new release this week, and close this issue when done. 👍

**Comment by hubertusputu1** [comment]
@npaton Ok noted.
