### ISSUE TITLE
add `game.index` field

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#14]
it can be a global game index within the entire experiment deployment (i.e., not within the treatment or within batch).

This is for humans to be able to reference games: Like "Game #3 had interesting results".

**Comment by npaton** [comment]
[`Game.index`](https://empiricaly.github.io/docs/api#game-object) in [Empirica v0.2.0](https://github.com/empiricaly/meteor-empirica-core/blob/master/CHANGELOG.md#020-2018-11-25)

I also added an auto-incrementing index on Players and Batches, thought they might come in handy.
