### ISSUE TITLE
Error in callbacks after updating Empirica Core

### ISSUE THREAD

**Issue by jwburton** [empiricaly/meteor-empirica-core#140]
I recently updated Empirica Core and now encounter an error with callbacks whereby participants are passed directly from the lobby to the exit survey, skipping over the entire game protocol. 

The error log below explains that this is due to the "players" argument being deprecated.
![error-log-1](https://user-images.githubusercontent.com/53270059/84173738-9a02ed00-aa75-11ea-8905-346ef714ac03.png)

But when I use "game.players" instead, I get the following error:
```
   While building for os.osx.x86_64:
   server/callbacks.js:6:28: /Users/jason/my-experiment/server/callbacks.js: Invalid left-hand side in arrow
   function parameters (6:28)
   
     4 | // the first onRoundStart. It receives the game and list of all the players in
     5 | // the game.
   > 6 | Empirica.onGameStart((game,
   game.players) => {});
       |                             ^
     7 | 
     8 | // onRoundStart is triggered before each round starts, and before onStageStart.
     9 | // It receives the same options as onGameStart, and the round that is starting.
   
=> Your application has errors. Waiting for file change.
```

Note that I'm using the stock callbacks from the "my-experiment" files provided on the [quick start tutorial](https://empirica.ly/docs/quick-start.html). 

Could you please provide guidance on troubleshooting this?

**Comment by JamesPHoughton** [comment]
You should be able to do just:
```javascript
Empirica.onGameStart(game => {});
```

The deprecation warning is trying to suggest that you use `game.players` within the arrow function if you need access to the `players` object, as it won't be passed to the callback separately. This is ok, because the `players` object is an element of the `game` object. =)

In your particular example, you aren't running any new code inside the callback (ie, the `{}` is empty} so you shouldn't have to worry about it.

**Comment by JamesPHoughton** [comment]
Just so you have it handy, here's the syntax for the other callbacks, from the updated template game:
```javascript
// onGameStart is triggered opnce per game before the game starts, and before
// the first onRoundStart. It receives the game and list of all the players in
// the game.
Empirica.onGameStart(game => {});

// onRoundStart is triggered before each round starts, and before onStageStart.
// It receives the same options as onGameStart, and the round that is starting.
Empirica.onRoundStart((game, round) => {});

// onStageStart is triggered before each stage starts.
// It receives the same options as onRoundStart, and the stage that is starting.
Empirica.onStageStart((game, round, stage) => {});

// onStageEnd is triggered after each stage.
// It receives the same options as onRoundEnd, and the stage that just ended.
Empirica.onStageEnd((game, round, stage) => {});

// onRoundEnd is triggered after each round.
// It receives the same options as onGameEnd, and the round that just ended.
Empirica.onRoundEnd((game, round) => {
  game.players.forEach(player => {
    const value = player.round.get("value") || 0;
    const prevScore = player.get("score") || 0;
    player.set("score", prevScore + value);
  });
});

// onGameEnd is triggered when the game ends.
// It receives the same options as onGameStart.
Empirica.onGameEnd(game => {});
```

**Comment by npaton** [comment]
Thank you @JamesPHoughton. I believe this should solve your issue @jwburton. Feel free to comment here if you're having further problems. ⛵
