### ISSUE TITLE
Add checkbox to disable export of PII

### ISSUE THREAD

**Issue by npaton** [empiricaly/meteor-empirica-core#141]
By default, `player.id`, `player.urlParams`, and `player. lastLogin.ip` should not be exported as they can contain Personal Identity Information (PII).

Tasks:
- [ ] add checkbox to export, that is always checked by default that states: "Remove Personal Identity Information (includes the player ID, URL parameters, and IP address)". This sets a remove_pii flag in the export request sent to server.
- [ ] In server export, if the remove_pii flag is set, remove the fields listed above from the export

**Comment by JamesPHoughton** [comment]
In the same area, it might be nice to export (and potentially automatically retrieve) a player bonus `.csv`, formatted for MTurk or whichever platform is used to recruit participants.

**Comment by npaton** [comment]
@JamesPHoughton  That sounds good. If you have a link to the format(s) that would need to be in, feel free to create another ticket for that 👍
