### ISSUE TITLE
Missing roundIds field on games collection

### ISSUE THREAD

**Issue by hubertusputu1** [empiricaly/meteor-empirica-core#146]
Missing roundIds field inside games collection when the game is created

## Expected Behavior

roundIds should be on games collection

## Current Behavior

roundIds is missing on games collection

## Possible Solution

assign roundIds on games collection 

## Steps to Reproduce (for bugs)

1. checked it database, under games collection
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by npaton** [comment]
I think we should rather remove the roundIds field from the Game.

**Comment by hubertusputu1** [comment]
@npaton Ok noted.

**Comment by hubertusputu1** [comment]
> I think we should rather remove the roundIds field from the Game.

@npaton just checked if we remove the roundIds field from the Game, it could be a breaking changes for some of exist experiment. As i can see it here:

https://github.com/patondev/speed_dating_human_ai/blob/master/client/game/PlayerProfile.jsx#L8-L9

This experiment use `game.roundIds` field. Is it good for us to proceed this changes?

**Comment by npaton** [comment]
Yes, confirmed, we should not break existing experiments, so let's keep roundIds and make sure they are properly filed. 👍
