### ISSUE TITLE
Out of Memory issues on blank experiment on t2.micro

### ISSUE THREAD

**Issue by bchivers-stanford** [empiricaly/meteor-empirica-core#155]
I'm launching the "Quick Start" guide on a t2.micro, and run out of memory before ever launching the server.  

## Expected Behavior
I expect to be able to launch the server and see a blank experiment.

## Current Behavior
The server becomes unresponsive before launching the server

## Steps to Reproduce (for bugs)
Here are the commands run from EC2 creation to OOM situation

1. sudo apt update
2. NVM install (curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash)
3. Node install (nvm install node)
4. Meteor Install ( curl https://install.meteor.com/ | sh )
5. npx create-empirica-app my-experiment
6. cd my-experiment
7. meteor

## Context

I'm just trying to complete the "Quick Start".  

## Your Environment

t2.micro instance, Ubuntu 18.04

**Comment by joshua-a-becker** [comment]
How much memory do you have?  What happens if you add more?  Please share the error message you got.

**Comment by bchivers-stanford** [comment]
A t2.micro has 1GB of memory. I ran the same thing on a t2.medium (4GB memory), and saw a peak usage of ~2.5GB.  Maybe there should be some sort of "System Requirements" if a blank experiment needs 2.5GB of RAM?

**Comment by joshua-a-becker** [comment]
Do you have a swap file?  If so, how big is it?  If not, add a swap file, which is easier than adding hardware memory, sorry I didn't mention that before.  Try 8gb or maybe 16gb.

https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04

(I'll bring up the 'system requirements' thing to the other people who do docs.  It's not Empirica, it's Meteor that's using all the memory.)

**Comment by joshua-a-becker** [comment]
sorry for my inconsistency, swap file = page file

**Comment by bchivers-stanford** [comment]
Using a swap file worked!  

Thanks for bringing up the system requirements - I found out the hard way that the "Quick Start" isn't quick at all if you don't have enough RAM or disk space for swap.

**Comment by joshua-a-becker** [comment]
Maybe we also need a "slow start" including the setup and install.  Want to make it easy.

________________________________
