### ISSUE TITLE
Record and expose player status

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#16]
We want to be able to see if the player is online/offline, background/foreground (tab in the background or not) and idle/active (user events: click, mouse movement, etc.). something like `meteor-user-status` by mizzao: https://github.com/mizzao/meteor-user-status

**Comment by npaton** [comment]
New [status info on `Player`](https://empiricaly.github.io/docs/api#player-object) available in [Empirica v0.2.0](https://github.com/empiricaly/meteor-empirica-core/blob/master/CHANGELOG.md#020-2018-11-25).

**Comment by amaatouq** [comment]
@npaton this is AMAZING!!!!!!

**Comment by npaton** [comment]
Glad you like it. :) I assume you saw the rudiments of an admin UI for players. Still wonder if there should be another indicator to distinguish when the tab is clearly backgrounded (on another tab or window), which we can more or less distinguish. There are a few of problems with that:
- game designers might be tempted to be rigid about, while, sometimes you do need to go and fix something on another tab, and the game shouldn't probably depend on this
- it might not be 100% reliable (as is idleness already, lets be clear, it's difficult to be 100% sure about the state of things)

Where it might be useful:
- determining if a player was indeed not being very attentive with the game (which does require to assume the indicator is correct, but it might be helpful to confirm if you already had suspicions).
- maybe detecting (through timing) players that are multi tasking, playing as multiple players at the same time. Wow we're getting into the edge cases real quick here.

**Comment by amaatouq** [comment]
Yes--it is very cool. although the UI still has the 'under construction' section. But other than that, I think this will suffice for now! I think we should have another indicator to distinguish when the tab is clearly backgrounded. It is up to the experimenter how to interpret this (we can indicate in the documentation that this is not 100% accurate). But if someone gave no answers + was indicated as offline for a good period of time, then it is safe to assume that they did not put effort in the task.
