### ISSUE TITLE
Admin Batch time should be runningAt instead of createdAt

### ISSUE THREAD

**Issue by npaton** [empiricaly/meteor-empirica-core#164]
## Expected Behavior

When the Batch is running, in the Admin the time shown in the table (e.g. "10 minutes ago") should be `batch.runningAt`.

## Current Behavior

It's displaying `batch.createdAt`.

## Possible Solution
If the batch has started if should use `batch.runningAt` in that column. Before it's running, I don't know, it should display nothing?

**Comment by amaatouq** [comment]
The order of batches shown in the admin UI table should show the ones that are running (and finished) first ordered by runningAt. This should be followed by the ones that are "created" (but not running) ordered by createdAt.
