### ISSUE TITLE
Visual bug with game count for 'complete' batches

### ISSUE THREAD

**Issue by Karakaii** [empiricaly/meteor-empirica-core#178]
## Expected Behavior
When one creates a "complete" batch, and then creates a new one, the "Game count:" information should show 0 in the new batch (as it would have done when one creates the first batch). will show more than 0 games when creating the new one.

## Current Behavior
When one creates a "complete" batch, and then creates a new one, the "Game count:" information will show more than 0 games when creating the new one (e.g., 1).

## Steps to Reproduce (for bugs)
1. Go to a project's "/admin" path
2. Create a 'complete' batch with one game or more
3. Start creating a new 'complete' batch, and inspect the "Game Count" number before adding a game

## Context
This is not an important issue at all. I just thought you would want to know about a little thing like this. It was a little bit confusing at first for the person creating batches for the experiment.

## Your Environment
- Version used: 1.7.0 and 1.9.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 86 and Firefox 82.0.2 (64-bit)
- Operating System and version (desktop or mobile): desktop Windows 10 Home

**Comment by npaton** [comment]
![image](https://user-images.githubusercontent.com/9678/98208067-9cf80000-1f77-11eb-9395-ed93a5f52069.png)
