### ISSUE TITLE
Disable or Remove "New Player" and "Reset Current Session"

### ISSUE THREAD

**Issue by bchivers-stanford** [empiricaly/meteor-empirica-core#185]
I can't find a way to disable the "New Player" and "Reset Current Session" buttons in the header - this is not a capability I'd like to have participants use. 

## Expected Behavior
Some way to disable or remove these buttons in the header

## Current Behavior
I think they're just part of Empirica by default

**Comment by amaatouq** [comment]
All of these are disabled by default on deployment. In case you want to enable them on the deployment, you can do this in the settings file. 

```
{
  "admins": [
    {
      "username": "admin",
      "password": "admin"
    }
  ],
  "public": {
    "playerIdParam": "workerId",
    "playerIdParamExclusive": false,
    "debug_newPlayer": true,
    "debug_resetSession": true,
    "debug_resetDatabase": true,
    "debug_gameDebugMode": true
  }
}
```

**Comment by bchivers-stanford** [comment]
I'm not really sure what you mean by "on deployment".  What should the settings file look like if I want them disabled?

**Comment by amaatouq** [comment]
I mean these things appear in your localhost, but once you deploy it (e.g., on [Galaxy](https://galaxy.meteor.com/)) so other people can access your app, it will be disabled by default. 

In any case, you can always create a settings JSON file (e..g, `local.json`) and have this in it:
```
{
  "admins": [
    {
      "username": "admin",
      "password": "admin"
    }
  ],
  "public": {
    "playerIdParam": "workerId",
    "playerIdParamExclusive": false,
    "debug_newPlayer": true,
    "debug_resetSession": true,
    "debug_resetDatabase": true,
    "debug_gameDebugMode": true
  }
}
```
Then when run meteor with these settings: `meteor --settings local.json`

You can do the same with your `deployment.json` where you'll have to add additional information for the deployment (e.g,. if you were deploying on Galaxy):
```
{
  "admins": [
    {
      "username": "admin",
      "password": "demo"
    }
  ],
  "galaxy.meteor.com": {
    "env": {
      "MONGO_URL": "<URL to your production MongoDB>",
    }
  },
  "public": {
    "playerIdParam": "workerId",
    "playerIdParamExclusive": false,
    "debug_newPlayer": false,
    "debug_resetSession": false,
    "debug_resetDatabase": true,
    "debug_gameDebugMode": true
  }
}
```

**Comment by bchivers-stanford** [comment]
I've tried the `local.json` you have above, with `debug_resetSession` and `debug_newPlayer` as both true and false.  I start my project with `meteor --settings local.json`.  Both times, I am able to use the New Player and Reset Current Session buttons successfully.  Let me know if there's something else I should try or confirm.  Appreciate the help on this.

**Comment by npaton** [comment]
That should not be possible, it is something we use every day, so I am pretty sure it works (but we might have a new bug). Maybe it's a cache clearing option. Could you try to "hard" reload the page (clearing cache + reload). On chrome mac, you can do Cmd+Shift+R, on Windows, you can do Ctrl+F5 (other browsers: https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache).

Note, those values (`debug_resetSession` and `debug_newPlayer`) should be set to false.

**Comment by npaton** [comment]
My bad, I forgot, in development mode, these buttons will always be active. While developing locally, you can enable "production mode" by passing `--production` to meteor: `meteor --production --settings mysettings.json`. In production mode, these debug buttons/functions will be disabled by default.

**Comment by amaatouq** [comment]
ops -- let me correct myself. The enabling/disabling of these features in the settings file only works in production mode. In dev mode, it will always be enabled.

When you have real participants, you shouldn't be in development mode, but in deployment/production.

**Comment by bchivers-stanford** [comment]
The `--production` flag did it! Thank you both!

**Comment by npaton** [comment]
Note, for clarification, there are practical differences between development and production modes. In development, code is not optimized or minified, so it will run (slightly) slower but build faster for quicker development iterations ; in dev mode debug utilities and logging is enabled (such as these debug buttons, or React introspection capabilities). By default, meteor will run in dev mode. Production mode can be activated with that `--production` flag (though it's not really recommended to run in prod like this) ; it will be activated when deploying to Meteor Galaxy ; and it is activated when building with `meteor build`, which outputs final code than can be deployed manually to a server.
