### ISSUE TITLE
Add tool to quickly clean the database (but keep treatments, factors, and lobby settings)

### ISSUE THREAD

**Issue by Karakaii** [empiricaly/meteor-empirica-core#188]
Hello, 
This I feature that I think is useful and that I would like Empirica to have.

## Expected Behavior
I often want to 'clean' my database from my tests; namely, I want to get rid of all batches, games, players, logs, etc. so that I start clean and that, when I look at the database or download data, there are none of my previous development tests and checks left. However, it is quite cumbersome and annoying to manually delete each bit from the database (especially if you are starting the experiment in 5 minutes) and you don't always know what to delete. It would be great if there could be a button in the /admin (with a check like "write x to confirm that you want to wipe the database") that allows you to do this in one go. I would like to be able to keep the treatments, factors, and lobby settings, however.

## Your Environment
- Version used: 1.11.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 86.0.4240.193 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10 Home

Thank you :)

**Comment by amaatouq** [comment]
You currently can do that from the admin UI when you are in the development mode ("Reset games" is what you are asking for):
![Screen Shot 2020-11-11 at 11 04 03 AM](https://user-images.githubusercontent.com/1761268/98834819-a36df800-240d-11eb-841f-3acfbc1979ee.png)

To do that in deployment, you'll need to enable these options in your settings file with the `debug_resetDatabase` flag. For example:

```
{
  "admins": [
    {
      "username": "admin",
      "password": "demo"
    }
  ],
  "galaxy.meteor.com": {
    "env": {
      "MONGO_URL": "<YOUR DATABASE>",
    }
  },
  "public": {
    "playerIdParam": "workerId",
    "playerIdParamExclusive": false,
    "debug_newPlayer": false,
    "debug_resetSession": false,
    "debug_resetDatabase": true,
    "debug_gameDebugMode": true
  }
}

**Comment by Karakaii** [comment]
Thank you so much for your reply. This is really useful!
