### ISSUE TITLE
Remove (or change) identification page

### ISSUE THREAD

**Issue by bchivers-stanford** [empiricaly/meteor-empirica-core#197]
Hello,

I'd like to remove the page that asks for identification from a player.  This is the page that comes right after the Consent form.  If this identification is required to track the player, then I'm wondering if I can alter it so it randomly generates an ID and moves on.  

Let me know if more details are required.  Thanks!

**Comment by Karakaii** [comment]
Hi, 

Here are a few things you can do.

## URL queries
Firstly, if you deploy using a settings.json file, you can set parameters that will grab the id in the URL and skip this identification page. For example, in one of my projects:
`    "public": {
        "playerIdParam": "playerIdKey",
        "playerIdParamExclusive": false
    }`

For a fake example of an app with these settings, I can set the ids directly in the URL `https://myfakeapp.meteorapp.com/?playerIdKey=3333`
So, if you send the link to Prolific participants, for example, you can set their Prolific id to be a URL query that will be grabbed directly by your Empirica app. 

## Modifying the new player component
If you have updated your Empirica core to 1.11.0 or later, you can directly modify the identification page component.

In your `client/main.js` you need to set the component you will use for the identification page:
```
// Set the component for getting the player id

Empirica.newPlayer(PlayerId);
```

Then this the way I built my component for example. The important bits are the different **handles**.
You could modify this to have the component generate a random id for the player and set it with **handleNewPlayer(id)**.

```

import React, { Component } from 'react';
import { Centered } from "meteor/empirica:core";

export default class PlayerId extends Component {
    state = { id: "" };

    handleUpdate = event => {
        const { value, name } = event.currentTarget;
        this.setState({ [name]: value });
    };

    handleSubmit = event => {
        event.preventDefault();

        const { handleNewPlayer } = this.props;
        const { id } = this.state;
        handleNewPlayer(id);
    };

    render() {
        const { id } = this.state;

        return (
            <Centered>
                <div className="new-player">
                    <form onSubmit={this.handleSubmit}>
                        <h1>Identification</h1>

                        <p>
                            Please enter your student ID (e.g. the 8 digit number):
                        </p>

                        <input
                            dir="auto"
                            type="text"
                            name="id"
                            id="id"
                            value={id}
                            onChange={this.handleUpdate}
                            required
                            autoComplete="off"
                        />

                        <p className="button-holder">
                            <button type="submit">Submit</button>
                        </p>

                    </form>
                </div>
            </Centered>
        )
    }
}
```


I hope this helps.

Best wishes
Sam

**Comment by shawnzam** [comment]
We also use the settings file to skip the identification page. Our settings file also sets the admin password:

```
"{\"public\": {\"playerIdParam\": \"responseID\",\"playerIdParamExclusive\": false},\"admins\": [{\"username\": \"admin\",\"password\": \"$ADMIN_PASSWORD\"}]}"
```

**Comment by bchivers-stanford** [comment]
Thank you so much! Both of these methods work.

How did you find these solutions?  I don't really like using Issues as a "help!" section, but I couldn't find this answer in this repo or the webpage.

Best,
Brian

**Comment by amaatouq** [comment]
We definitely can do a better job with the documentation, and we are actively working on that. In the meantime, there is an Empirica slack with a `#tech-support-not-bug-reports` channel for these types of questions. Using GitHub Issues is fine too :)

**Comment by bchivers-stanford** [comment]
Could you post a link to the Slack channel? I can't find one

Thanks!!

**Comment by amaatouq** [comment]
Here you go: https://join.slack.com/t/empirica-ly/shared_invite/zt-5y98b811-1ATG7hv5tnkZy~NU7IoGqg
