### ISSUE TITLE
canceling game is not working as expected

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#2]
Stopping a batch from the admin UI no longer works correctly (after the recent fix). It is supposed to take the participant to the exit survey with `exitStatus ==  gameCancelled` however, it just redirects the participant to `No experiments available`

**Comment by npaton** [comment]
Ok, yeah, I overfixed the cancellation. So the expected behavior is, on batch cancel:
- player is in game: go to exit
- player is in lobby: go to exit
- player has entered their player ID (in intro steps): go to exit
- player has NOT entered their player ID: no experiment available

Correct?

**Comment by amaatouq** [comment]
Yes!

**Comment by npaton** [comment]
This was fixed in `empirica:core` v0.0.6.
