### ISSUE TITLE
lastUpdateBy field

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#20]
we currently have `updatedAt` for every record in the database. It would be nice to have `lastUpdateBy` field which would have one of three values: {'client', 'server', 'empirica'} to know who updated.

**Comment by amaatouq** [comment]
or we can have `updatedAt` and `lastUpdateBy` under `data` such that `lastUpdateBy` will only have two options: `{client, server}` .. while the top level `updatedAt` will always reflect the timestamp of when `core` updated the record.

**Comment by npaton** [comment]
The solution for this problem is actually better solved by #25. If this particular solution is needed, please reopen an issue with a description of the problem.
