### ISSUE TITLE
Problem with Galaxy deployment and version 1.12.0

### ISSUE THREAD

**Issue by jwburton** [empiricaly/meteor-empirica-core#205]
## Expected Behavior
- Deployed version of the experiment to run the same as the local version on my machine when using Empirica Core 1.12.0.

## Current Behavior
- Experiment performs fine during local testing, but is a blank white screen when deployed to Galaxy,
- Here's the error messages when checking the Javascript console on the site of the deployed experiment:
<img width="1363" alt="Screenshot 2021-01-05 at 15 52 18" src="https://user-images.githubusercontent.com/53270059/103668074-9fbea380-4f6e-11eb-853d-f3b376407f36.png">

## Possible Solution
- Unknown.

## Steps to Reproduce (for bugs)
- Deploy an experiment using 1.12.0 to the Galaxy (?). Unsure if there is something specific to my experiment code, but can share privately if it's helpful.

## Context
- Unable to run experiment

## Your Environment

- empirica:core 1.12.0
- Local tests done on MacBook Pro with macOS Catalina 10.15.7
- Deployed to Galaxy 12GB container with MongoDB M20 Cluster

**Comment by hawkrobe** [comment]
I can confirm and reproduce this bug even when running locally with `--production` flag.

**Comment by npaton** [comment]
https://github.com/empiricaly/meteor-empirica-core/blob/8eec8f2ebedd7def7d059af0facadbd40f46a52e/ui/components/Public.jsx#L5 `public.public`
