### ISSUE TITLE
Exposing an explicit callback for player disconnect

### ISSUE THREAD

**Issue by hawkrobe** [empiricaly/meteor-empirica-core#206]
## Expected Behavior

Dropouts are an unfortunate reality of big online experiments and we usually want something to happen when a client disconnects or goes idle. For example, we may want to go ahead and end the game and send the remaining players to exit surveys, we may want to pause the game and notify the other players that they will be waiting for 30 seconds for the offline player to reconnect, or, following #91 , we may want to replace the disconnected player with a new participant who has been standing by, or we may even want to replace them with a bot. Because there are a broad range of different ways that researchers may want to handle dropouts, it would be valuable to expose a more flexible way of specifying the desired behavior in the API. 

## Current Behavior

Currently, disconnection triggers the `.onClose()` meteor callback, which leads [player status to be updated to offline](https://github.com/empiricaly/meteor-empirica-core/blob/6b6364172a7db9bc843c000c5925eea378d2501a/startup/server/connections.js#L61). However, this update happens directly at the level of the Mongo collection/schema, so as far as I can tell, it doesn't get picked up by any of the current callbacks exposed in the API (e.g. `.onSet()`). 

I think we can always work around this by setting a custom polling callback with `Meteor.setInterval()` to loop through players and check whether they are still online (which appears to be how the [`ActivityMonitor`](https://github.com/empiricaly/meteor-empirica-core/blob/88fe9e42b617f150107114e1b78ec69bb203aa2e/lib/monitor.js) works), but this is not entirely in the spirit of React/Meteor and can either (1) lead to race conditions if the interval is too slow or (2) get expensive if the interval is too fast. 

## Possible Solution

Ideally, there would be an `Empirica.onDisconnect((player, status) => {})` callback exposed, which would allow researchers to implement their custom disconnect logic. In principle, this could also be triggered on idleness or other status changes, in which case it might make more sense to call it `Empirica.onPlayerStatusChange` or something.

For what it's worth, this is something [nodeGame](https://github.com/nodeGame/nodegame/wiki/Disconnections-and-Reconnections-v6#size-handlers) handles pretty nicely (e.g. the default behavior is notifying other players and giving a short window to wait for a reconnection before proceeding).

**Comment by amaatouq** [comment]
Now we have this in v2.

**Comment by JamesPHoughton** [comment]
Here's what I use at the moment:

```js
// callbacks.js
const playersForParticipant = new Map();

Empirica.on("player", async (ctx, { player }) => {
  const participantID = player.get("participantID");
  playersForParticipant.set(participantID, player);
}

function playerConnected(player) {
  console.log(`Player ${player.id} connected.`);
}

function playerDisconnected(player) {
  console.log(`Player ${player.id} disconnected.`);
}

Empirica.on(TajribaEvent.ParticipantConnect, async (_, { participant }) => {
  const player = playersForParticipant.get(participant.id);
  if (player) {
    playerConnected(player);
  }
});

Empirica.on(TajribaEvent.ParticipantDisconnect, (_, { participant }) => {
  const player = playersForParticipant.get(participant.id);
  if (player) {
    playerDisconnected(player);
  }
});
```

Not sure if there is an updated syntax, I haven't poked around with it in since the summer...
