### ISSUE TITLE
Improve JSON export

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#21]
The json data files that are produced by Empirica do not have a valid JSON structure.

They currently look like this : 
```JSON
{"Name1": "value", "Name2": "value"}
{"Name1":"value" ,"Name2": "value"}
...
```

Which is easier to loop over and insert each row as a document in a non-relational database. But alternativly, we could have each block to be embedded in a larger structure, like this :

```JSON
{
"_id 1" : {"Name1":"value","Name2":"value"},
"_id 2" : {"Name1":"value","Name2":"value"}
}
```

which will be readable by typical JSON parsers.

**Comment by npaton** [comment]
Proposal: Add new "JSON Line" export that would cork like our current JSON export, and update the JSON export to export an array as such:

```json
[
  { "_id": "1", "Name2": "value" },
  { "_id": "2", "Name2": "value" }
]
```

**Comment by npaton** [comment]
http://jsonlines.org/
