### ISSUE TITLE
Intro resets when the batch starts

### ISSUE THREAD

**Issue by nwrim** [empiricaly/meteor-empirica-core#230]
When participants are reading the instructions (they are in the opaque state in the batches) and the batch starts, the instruction that the participants are reading refreshes and the page goes to the first page.

## Expected Behavior

Participants should be able to keep reading the instructions without returning to the first page in the instruction.

## Current Behavior

Participants return to the first page when the batch they were originally assigned to starts, perhaps due to them moving to another batch.

## Possible Solution

I do not have a possible solution, sorry!

## Steps to Reproduce (for bugs)

1. I used Abdullah's CSOP experiment (http://github.com/amaatouq/room-assignment-csop/) locally to observe this behavior.
2. After setting up a configuration using `example-config.yaml` file in the directory, start two batches using the "team" treatment, one game each.
3. Start a new player, move to the quiz page but do not solve the quiz.
4. Start three additional players, submit the quiz (answer should be 3, "We will submit only one answer as a team and therefore we will all get the same score.", 0, 100, Room 102, Room 102/104) for the additional players.
5. The game starts for the latter three players, but the instruction page goes to the initial page for the first player who did not submit the quiz yet.

## Context

The instruction for the task is quite long, so participants get frustrated and leave the task without participating (and sometimes send angry emails). Thus, it makes the attrition rate of participant go up, negatively impacting research.

## Your Environment

- Version used: empiricia:core 1.15.2 / empricia:slider: 0.0.3
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 88.0.4324.96, node.js 12.21.0
- Operating System and version (desktop or mobile): desktop, Ubuntu 20.04.1
- Link to your project: http://github.com/amaatouq/room-assignment-csop/

Let me know if anything is unclear! I am working with Abdullah and can be reached in Slack also.

**Comment by npaton** [comment]
More feedback about this issue, from Slack:

> Robert Hawkins:  Yeah we recently got a comment from a participant that sounded similar:
> I had a problem before getting to the actual game, the rules kept refreshing and i needed to click thru them again, then it would reset again; it started when the graphic of how the game looks was shown and ended after entering the "waiting room" where i was waiting for other participants (after reading everything i just clicked really fast "next" to make it to the actual game before the reset)	

> Jin Hyun Cheong:  I can confirm that I’ve been experiencing this too and would love to see a fix.
> My instruction is also comprised of 8 pages. Would love to see a patch so that even when a participant is moved to a different game/batch they can still continue the instructions from where they were instead of back from the beginning.  My monkey patching solution currently is that I save their answers through the tutorial so they can cycle back to where they were quickly even if they start over.

**Comment by npaton** [comment]
We have pushed a partial fix. The player should now be brought back to the correct intro step after changing batches. Unfortunately, we might not restore the state of the given intro step they were on. We recommend setting data on the player (using player.get/set instead of React's setState), which will restore the state automatically. We will be looking into improving this situation if possible in the future, but hopefully this improves the user experience in the mean time.


This will be release in the next release, coming out very soon (today hopefully).
