### ISSUE TITLE
Stages are sometimes out of order in the breadcrumb

### ISSUE THREAD

**Issue by npaton** [empiricaly/meteor-empirica-core#24]
It was reported that stages can sometimes be displayed out of order in the Breadcrumb.

The reason for this is known at this point: the stages array attached to the round object in the UI stack is not sorted. Nor is the rounds array on the game object. Adding sorting should fix the problem.

Note that this issue should not affect the order in which the rounds or stages are played. But it would affect anything using those arrays directly, and only the breadcrumb does by default.

**Comment by npaton** [comment]
@Dan5Playground This should be fixed, you can pull with `meteor update empirica:core`. If it's working for you, you can close this issue.

**Comment by Dan5Playground** [comment]
Thank you.
