### ISSUE TITLE
Players are sent to gameFull when they should be sent to the next batch

### ISSUE THREAD

**Issue by Karakaii** [empiricaly/meteor-empirica-core#255]
I am running a big multiplayer study where I need many people to come in at the same time to form groups. To make sure my groups fill in and that I don't get games that half fill and then fail at the lobby, I open multiple batches, each with a game of the same treatment. Once the first batch is complete, participant are sent to the next one. However, in that process, I get a few participants who are sent to gameFull instead of the next batch.

**Comment by Karakaii** [comment]
Hello, 
An update on this. We had 1383 participants, 92 were sent to gameFull. 
Whilst this is small percentage, a gameFull should not have occurred.

For most of the participants we didn't have a special timing. People just came in from the recruitment platform. For some of the participants we had a system where we had participants come in at the same time to the consent page (not the lobby itself).

**Comment by npaton** [comment]
Hey @Karakaii. We have managed to reproduce the issue and are working on a fix. Hopefull out today. 🙌

**Comment by Karakaii** [comment]
Awesome! Thank you!

**Comment by npaton** [comment]
@Karakaii Let us know if it does indeed fix your issue. We were pretty convinced we could reproduce it, but it's hard to validate against 100s of players in a real-world situation. 👍
