### ISSUE TITLE
closing the browser does not remove the player from the lobby

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#3]
Now when a player closes the browser while waiting in the lobby, they keep being in the lobby and are not dropped.

**Comment by npaton** [comment]
I cannot reproduce this issue. Players are removed from the ready queue when the leave the lobby (close browser or navigate away from site). Could you provide me with steps to reproduce? Thanks!

**Comment by npaton** [comment]
@amaatouq Have you encountered this issue again? It's working for me.
