### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by npaton** [empiricaly/meteor-empirica-core#31]
Add API documentation to website. Also basic concepts.

**Comment by npaton** [comment]
Add lifecycle diagram.

**Comment by npaton** [comment]
I didn't go for a life cycle diagram, it's text, I couldn't figure out the diagram, without probably spending a couple days on it. But I think it might still be helpful.

That and the API docs and the concepts page, all could use some love, it's probably all a bit rough, but as a first pass, I think it's all there.

- [API](https://empiricaly.github.io/docs/api)
- [Life cycle](https://empiricaly.github.io/docs/lifecycle)
- [Concepts](https://empiricaly.github.io/docs/concepts)

While writing the API docs, I came across a few discrepancies in the API and went ahead and fixed them. That will break current core. Sorry, but I think it's still a better time to clean up before v1.

The breaking changes changes (I can remomber) are:
- `onSet`/`onAppend`: I removed the `players` field, as it's already in the `game`: `game.players`
- `gameInit`: now only has one parameter, `game`, I removed `treatment`, as it accessible through `game`: `game.treatment`

That's all I can remember. I also noted that the default Consent contains a reference to the experiment being an MIT experiment. While I imagine most people will change the Consent text, maybe the default could be less specific?

CC @amaatouq

**Comment by joshua-a-becker** [comment]
loving these docs.

for lifecycle, I'm not missing the diagram--it's very clear as is.

a lot of the questions i had myself were around the game assignment and creation---this of course is about to change a lot so i'm not suggesting any additions to the doc at this time, just flagging this topic as something to keep in mind for future docs

**Comment by joshua-a-becker** [comment]
right now, it looks like object (player/game/etc) methods are not defined

E.g., i'm intriguied by this "player.append()" method which i did not know existed!
