### ISSUE TITLE
Create "Your first experiment"

### ISSUE THREAD

**Issue by npaton** [empiricaly/meteor-empirica-core#32]
Create simple Player's Dilemma tutorial from create-empirica-app to running the first experiment, including a little bit of UI love (blueprint? bootstrap?).

KEEP SIMPLE! :)

CC @joshua-a-becker

**Comment by joshua-a-becker** [comment]
apologies for my extreme delay in getting this out!

i've submitted a pull request for a draft of this, it might be a bit rough around the edges with some formatting

some of the features i included in the demo app are a bit arbitrary (e.g., having images for some tasks and not others) and this is designed to show people how to use Empirica to make flexible apps... and inspired by my own experiments

demo app at https://github.com/joshua-a-becker/first-empirica-experiment

i need to check that all the code in the final draft is consistent with the final version of the demo app

Known issues
- i have yet to check that the local URL reference to 'quickStart' is correct
- needs a URL link to the final version of the demo; i'm not sure where that will be stored
- a question for verification... is this true:  every time `player.round.set` is called, this triggers a database call which the MongoDB server must route causing activity in both the DB and the Meteor server

**Comment by joshua-a-becker** [comment]
@amaatouq not sure whether i should try to proceed at the moment---

i still need to update the git repo with the sample code (as per your comments) but the 'game' object in Empirica.gameInit() doesn't contain the players object so its broken as of now.

upgraded to 0.2.0 but got the error reported in #35

**Comment by npaton** [comment]
>upgraded to 0.2.0 but got the error reported in #35

In [0.3.0](https://github.com/empiricaly/meteor-empirica-core/blob/master/CHANGELOG.md#030-2018-11-27), the issue from #35 should be fixed, and `game` in `gameInit` should contain the players.

> a question for verification... is this true: every time player.round.set is called, this triggers a database call which the MongoDB server must route causing activity in both the DB and the Meteor server

Yes, every `set()` call will save the given piece of data in the DB, through the server. The data will also be disseminated across all clients. This can be costly, but only for very high data refresh rates, or large amount of players in a single game. Though I would not bring that up in an intro tutorial. ;)

I took a quick look at the code, looking like a good start I think. A quick prettier pass, and a few adjustments, and it looks good to me. To do the review, the ideal would be a PR, so we can review in once place and do the last few iterations.

As mentioned before, I really want the very core tutorials to be in the empiricaly org. So I propose to create a new repo at `empiricaly/your-first-experiment` that will start empty, and you can do a PR to import everything, we review it together and merge. It would be great if you could change the Readme to be a 1-2 paragraph intro to the repo with a link to the official docs on empiricaly.github.com (we'll move to the proper domain soon), and a credits section where you should add your credits and a reference to the origin repo.

I haven't created the repo yet, I want you guys to tell me if you agree with this first. ;)

CC @amaatouq

**Comment by amaatouq** [comment]
Sounds good to me!

**Comment by joshua-a-becker** [comment]
makes sense!  i have gotten on the prettier train, but i haven't pushed my changes yet b/c its broken code right now until i can get 0.3.

what other adjustments?

style question:  with the new `Empirica.gameInit(game)` form, do you prefer to use `game.player` throughout or define `const player=game.player` at the top?

> every set() call will save the given piece of data in the DB, through the server. The data will also be disseminated across all clients. This can be costly, but only for very high data refresh rates, or large amount of players in a single game. Though I would not bring that up in an intro tutorial. ;)

i disagree somewhat.   if you use a text input form, then it is a pretty high data refresh rate since it updates on every key press.  and as you know i advocate for a design that is friendly to large groups of simultaneous players.  even if you're not running large conditions, you likely will want to be able to run many conditions at once.   BUT my current mindset is due to the single-core implementation.   when i can take advantage of multi-core servers, i won't be concerned about data cost.

but i won't argue beyond this if you want to take that paragraph out of the tutorial!

**Comment by amaatouq** [comment]
> makes sense! i have gotten on the prettier train, but i haven't pushed my changes yet b/c its broken code right now until i can get 0.3.

You just need to run `meteor update empirica:core` in the directory. It is already pushed.

> i disagree somewhat. if you use a text input form, then it is a pretty high data refresh rate since it updates on every key press.

key press is super fine. The reactivity is dealt with well by meteor. Even using  `player.stage.set()` on a continuous slider `onChange()` with 60 people online, won't be noticeable. If faster update rate is possible (i.e., 100 calls / sec or something), then the trick is to use `_throttle()` + session. We will probably add this as an advanced example somewhere in the doc later!

**Comment by npaton** [comment]
> i disagree somewhat. if you use a text input form, then it is a pretty high data refresh rate since it updates on every key press. and as you know i advocate for a design that is friendly to large groups of simultaneous players. even if you're not running large conditions, you likely will want to be able to run many conditions at once. BUT my current mindset is due to the single-core implementation. when i can take advantage of multi-core servers, i won't be concerned about data cost.

I understand. I should explain my reasoning about this. In short, we do want to make thing efficient enough that it is generally not a concern, 90+% of the time. And we want to make scaling horizontal (multi server) and (nearly) linear. We are not there yet for sure, but this is the philosophy and I do want to overall give that feeling in the docs. I am not at all opposed to some documentation about performance considerations, explaining the state of things, where we are and where we want to be, tips and tricks, how to evaluate performance, etc. But I do not think it is something of importance in the intro tutorial, maybe in an "Advanced" section, a "Performance" document.

We could go into further questions about what is the actual impact of saving data this much (hint: we don't know until we measure, as always with performance), how we want to optimize in the future (for ex. we can optimize the `data` field so there is **a lot** less traffic over the network), or how we want to change the API for more control (for ex. allowing the game designer to choose which fields to sync), or, the holy grail, make it scale linearly on multiple servers (which is harder than it sounds like), etc.

Quick note about this particular example. While I really wouldn't be worried about the cost of saving on each keystroke, there is absolutely no obligation to for the game designer to store the data with `set()` all the time. It is common good practice to use local state for a form until submit time. This kind of simple optimization, and others like the throttling Abdullah was mentioning, are plenty, and we can document their usage. But by default, start simple, optimize later, when you know where the bottlenecks are. The intro tutorial is here to start simple. As they say "premature optimization is the root of all evil". 💃 

> but i won't argue beyond this if you want to take that paragraph out of the tutorial!

My apologies, I have not read your intro yet, I plan on doing that as soon as possible, but I have an overloaded week ahead, so I am sorry if I do not make it this week. In any case, I am looking forward to reading it and confident it is a great step forward!

**Comment by joshua-a-becker** [comment]
ok so the repo is updated & prettified

**Comment by amaatouq** [comment]
ok, I'll close this one. We will revise this again in later milestones. @joshua-a-becker can you please update the `Your First Experiment` in the doc with the URL for the repo?

**Comment by npaton** [comment]
My apologies for the delay, scheduled and unscheduled tasks have eaten up my week. I will be working on this over the weekend if there's still anything to do. I think there is at least a code review and merge to be done. And I will also move the website to the official domain.

**Comment by joshua-a-becker** [comment]
sorry for my delay!
-- removed node_modules and added to .gitignore in https://github.com/empiricaly/your-first-experiment
-- added link to github to instructions


https://github.com/empiricaly/your-first-experiment/pull/1
https://github.com/empiricaly/empiricaly.github.io/pull/3
