### ISSUE TITLE
Desired props not available to custom gameLobby

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#36]
Desired props are not available to custom gameLobby using Empirica API.

## Expected Behavior
I would expect all the same props to be available to the component passed to `Empirica.lobby()` that are used in the core `GameLobby.jsx` component.  

## Current Behavior
lobbyConfig is not available (also timedout but that could be calculated given lobbyConfig)

## Possible Solution
Pass these props to the custom lobby component.   OR give the gameLobby prop the details of the lobbyConfig.

I'd offer to implement this and post a pull request, but I have been unable to figure out where in core this happens!

## Context
I like my lobby to say, "Waiting up to X seconds for other players" where X is the timeout lobby config.

- Version used:  core 0.3.0

**Comment by npaton** [comment]
Seems fair. We are fetching it in `GameLobbyContainer.jsx`.

**Comment by hubertusputu1** [comment]
Hi @joshua-a-becker , this issue will be fixed in the next release. Thank you.
