### ISSUE TITLE
Expose "No Batch" component to experimenter

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#38]
Just a suggestion---

## Expected Behavior
Like Empirica.breadcrumb() and Empirica.lobby() it is desirable to be able to set the "No Experiments Available" to custom design

## Context
I do not find it desirable to use experimental language for subjects, and would prefer to use MTurk-like language such as "task."  Who likes being experimented on??

People might also want to put custom messaging on when to return, compensation, etc.

**Comment by npaton** [comment]
Agreed. I'd like to expand the possibility of customizing any screen. It would be great if we could list all the missing ones here so I can add them at once. Are there others still missing?

**Comment by joshua-a-becker** [comment]
yes---the "About" section.  i'll create an issue for that, and see if I can figure it out this weekend, as my first attempt at exposing something to the API.  if that works, i'll (eventually) circle back to this issue.

**Comment by npaton** [comment]
Great! It should be relatively easy, you can take example on the other exposed components. Thanks!
