### ISSUE TITLE
Lobbies attached to incorrect lobbyConfig

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#40]
I'm still figuring out the details but want to report this possible bug because it's invisible, and experimenters may not know its happening (but it could still cause unexpected behavior)

## Expected Behavior
Batches should be linked to the lobby assigned upon creation in the GUI.

## Current Behavior
After creating a new lobbyConfig, and creating a new batch with that new lobbyConfig, it is running with old lobbyConfigs.  Examination of the db confirms that the batch is assigned to lobbies which are assigned to the old lobbyConfig.

After archiving that lobby, then making yet another new one---the new one attaches.

## Possible Workaround
Don't archive batches.

## Possible Solution
not sure---don't see an immediate problem in `AdminNewBatch.jsx`

## Steps to Reproduce (for bugs)
1. create minimal conditions for group, including lobby with 300-second fail setting
2. create batch
3. create new lobby with 5-second ignore setting
4. archive your first lobby
5. create new batch with new lobby

(these particular lobby settings are just so you can easily verify you've got the wrong lobby.  this can also be seen by inspection of the database)

## Context
The biggest concern is that you can't really tell you're not getting the correct lobby config--there's no way except by looking at the database, unless you're using a custom waiting page (which I am) that reports some details from the lobby config.

**Comment by joshua-a-becker** [comment]
Update:  this may be linked to import/export.  It may occur only when importing into an app that already has factors/treatments/lobbies/etc.

**Comment by joshua-a-becker** [comment]
the problem seems to re-assert itself after an import, when the lobby is created before the import.

**Comment by npaton** [comment]
Thanks @joshua-a-becker. So steps are:

1. Create a lobby config (A)
1. Import other lobby configs (say, B and C)
1. Create a batch (1) with lobby config (B)
1. I'm not sure here, batch (1) has lobby config (A)?

I'm not sure the steps to reproduce. 👯‍♂️

**Comment by amaatouq** [comment]
Are you sure you are not in debug mode @joshua-a-becker? it is buggy likr this.

**Comment by joshua-a-becker** [comment]
see updated comment with steps to reproduce--this is not tied to the import, that was a red herring.  it appears as though somehow archived lobbies are getting attached to new batches.   can't tell why.

the easy workaround, it *seems*, is to not archive batches.

**Comment by joshua-a-becker** [comment]
if i had to guess, the issue lies entirely within AdminNewBatch.jsx and the fact that archived lobbies are filtered out for the display, but i can't see where the mis-assignment would come in.

**Comment by npaton** [comment]
With the following steps:
1. create minimal conditions for group, including lobby with 300-second fail setting
1. create batch
1. create new lobby with 5-second ignore setting
1. archive your first lobby
1. create new batch with new lobby

I cannot reproduce this issue. The correct lobby configurations are attached. Are those the right steps to reproduce?

**Comment by joshua-a-becker** [comment]
should be.  i'll check again.  i used the your-first-experiment demo, so i'll try again with the default create-empirica-app to be sure everything is totally up-to-date and default.  i've experienced this across several apps, and with both my own local server as well as meteor galaxy.  it's somewhat inconsistent so i'll see if i can find a more reliable reproduction.

**Comment by npaton** [comment]
Ok I think I actually might have found the cause. The default lobbyConfig selected when adding a treatment to a batch was selected from all lobbyConfigs, including archived ones. I pushed a fix (`meteor update empirica:core`). I am not 100% sure this was the issue from the description. Let me know if this fixes your issue.

**Comment by joshua-a-becker** [comment]
cool that sounds likely to be the issue.  i'll re-open if i ever encounter this problem again.

**Comment by joshua-a-becker** [comment]
all seems to be working fine :)
