### ISSUE TITLE
add endgame method to player object

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#42]
Ideally after the last stage of the last round, the player should not wait for other players to submit. Having a method such as `player.endGame()` that takes the player directly to the exitSurvey would achieve this.

**Comment by npaton** [comment]
Yes, that is definitely something we want to do and have already talked about. I don't know exactly when we'll get there but it's definitely happening sooner or later.

**Comment by joshua-a-becker** [comment]
whoops accidentally re-created this issue.  i recommend closing this one and keeping the more detailed https://github.com/empiricaly/meteor-empirica-core/issues/52

@eamanj --- i've started some basic functionality for this, which should serve for your purposes, and help to test it.  available in the "player.endGame" branch at https://github.com/joshua-a-becker/meteor-empirica-core/ 

current issuse:  does not end game if all players quit.  keeps players in roster, so rounds don't advance without them.  all it does, basically, is create a method to set an exitAt/exitStatus.
