### ISSUE TITLE
bots method does not receive secondsRemaining

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#44]
It seems the last argument is not properly passed to the method. I log it and it seems to be the same as the bot object and not the actual number of seconds remaining in the stage as an integer.

**Comment by npaton** [comment]
I pushed and update that should fix this issue, please run `meteor update empirica:core` and let me know if it's working. Thanks!

**Comment by eamanj** [comment]
worked. thanks!
