### ISSUE TITLE
Experiment progression gets stuck after about an hour of play

### ISSUE THREAD

**Issue by chri4354** [empiricaly/meteor-empirica-core#47]
We've had a couple of games in production getting stuck in this way. The game clock goes negative and the next round never starts. We aren't seeing any errors in the logs. But we've noticed the games are getting stuck right around the 60 minute mark. 
The timer went negative, no error in the console logs, players were just waiting for the next round to start
It might be a database problem, as one of the turkers got this message "Waiting for server response...
Please wait until all players are ready. If this takes more than 5 seconds, please Refresh the page." (refreshing did not help). 

Screenshots sent by turkers are available:
https://i.gyazo.com/e3b4bf3a6ba3e502ae2512282c8ebb41.png
https://gyazo.com/cb2728329f8fc6f54e79c1b3f4c9d9da
![turkers](https://user-images.githubusercontent.com/8029342/52502610-3599fa00-2bb1-11e9-9f3e-9bd4d324ef41.png)

**Comment by npaton** [comment]
I believe I have found the source cause for this issue. It was related to an old mechanism still in place for checking when to transition to the next stage, where we would use an estimated end of game time to scope our game object queries. That estimated game time was accounting for some buffer time we add in between stages, but for a game with a large amount of stages, the extra time added to the estimated end of game was not enough and we would stop updating the game.

I want to eventually remove this estimated game finished check. In the mean time I have greatly increased the extra time added to this field, so games with many stages should work now.

Update your experiment code with: `meteor update empirica:core`

Please reopen if you are seeing issues.

**Comment by chri4354** [comment]
@npaton , has this issue been fixed also on the old core? We need to use the old core because it seems the only one able to sustain large groups (>10 players).

**Comment by npaton** [comment]
I did backport this fix to the old core: https://github.com/empiricaly/empirica/commit/a2c00da2453144f5294dc8afe8610f889cc1f9ef
