### ISSUE TITLE
`round.set` function eliminates leading and trailing whitespace in value

### ISSUE THREAD

**Issue by askyel** [empiricaly/meteor-empirica-core#51]
## Expected Behavior

`round.set` saves the exact string value provided

## Current Behavior

`round.set` removes leading and trailing whitespace when setting the value

## Possible Solution

Remove an unnecessary trim or strip function?

## Steps to Reproduce (for bugs)

Bug occurred in [artwork gender bias experiment ](https://github.com/amaatouq/artwork_gender_bias/blob/master/client/game/TaskResponseText.jsx) before workaround of buffer characters was added.

## Context

When a user is putting text into an html textarea while writing a response, there will usually be trailing whitespace as they break between words or lines. If we are updating the response data stored for the round in real-time, trimming out the whitespace causes an issue of the user not being able to make these breaks at the end of their input string in progress of writing.

## Your Environment

- Version used:
- Chrome: Version 72.0.3626.109 (Official Build) (64-bit)
- Desktop MacOS operating system
- Link to your project: [https://github.com/amaatouq/artwork_gender_bias/blob/master/client/game/TaskResponseText.jsx](https://github.com/amaatouq/artwork_gender_bias/blob/master/client/game/TaskResponseText.jsx)

**Comment by npaton** [comment]
Thank you for the bug report! I pushed an update to fix the issue (`meteor update meteor:core`), please reopen if you are still seeing the issue. ⛵️
