### ISSUE TITLE
Allow player to skip remaining rounds

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#52]
picking up from:
https://github.com/empiricaly/empirica/issues/59

## Expected Behavior
Feature:  allow player to skip remaining rounds, get an exitStatus, and show `ExitSteps`

## Current Behavior
All players must complete all rounds.

## Possible Solution
1. ✔️  create a new exitStatus "finishedEarly"  (`players.js`)
2. ✔️ create a new method player.endGame (`api\players\methods.js`, `api\player-stages\augment.js`)
2b.  ✔️  add method to `api\games\create.js` so its available during init
3. remove players with `exitStatus==finishedEarly` from check in `api\stages\finish.js` so that their status isn't updated again at game end
4. figure out how to end game if all players finish early [not sure how this part works]
5. ensure no problematic interactions [the hard part]
6. remove player from check when round is finished (so other people don't wait for someone who is gone)

## Context
For my current purpose, I want to be able to bump people during `gameInit` in the event that initial conditions are not satisfactory.

Other people have also requested this feature because once a player is done the very last round, there is no need for them to wait on other players.

**Comment by joshua-a-becker** [comment]
I'm going to work on this feature today.

**Comment by joshua-a-becker** [comment]
#1 and #2 done, going to use this a while and see if any problems emerge.

available in the commit ref'd below

**Comment by joshua-a-becker** [comment]
extra step taken to make available during game init

**Comment by npaton** [comment]
Thank you for your help on this. Feel free to create a Draft Pull Request so we can keep updated on the code changes. ;)

**Comment by joshua-a-becker** [comment]
will do!  steps 1 & 2 were easy, steps 3-5 will likely take me much longer to complete

**Comment by joshua-a-becker** [comment]
known issue--players' statuses are still set to "finished" upon stage finish, added to to-do list above

**Comment by amaatouq** [comment]
@npaton we have this now, no?

**Comment by npaton** [comment]
We do. You can now call `player.exit("custom exit reason here")`. The player will be sent to the exitSteps.

The `player.exitStatus` will be set to `"custom"` and `player.exitReason` will contain the custom exist reason given when calling `player.exit(reason)`.
