### ISSUE TITLE
Uncaught ClientError: Last activity at is not a valid date

### ISSUE THREAD

**Issue by askyel** [empiricaly/meteor-empirica-core#57]
![image](https://user-images.githubusercontent.com/7734809/55257710-59c79e00-5226-11e9-8041-0b14a0d3f4ab.png)

This occurred after using the `$ meteor add empirica:core` in the project directory and then trying to run the project with `$ meteor`.

## Expected Behavior

I was expecting the project to run normally.

## Current Behavior

The project cannot run because of this issue.

## Possible Solution

I've changed timezones to two hours behind, this might be affecting the timestamp?

## Steps to Reproduce (for bugs)

1. `$ meteor create . --release 1.8`
2. `$ meteor add empirica:core`
3. `$ meteor`

## Context

Trying to add empirica core package to meteor project.

## Your Environment

- Version used:
Chrome: Version 72.0.3626.109 (Official Build) (64-bit)
- Desktop MacOS operating system

**Comment by amaatouq** [comment]
It should be: 
npx create-empirica-app my-experiment
cd my-experiment
meteor

**Comment by npaton** [comment]
@askyel A valid Empirica app is depending on a few other npm packages, which are added by `create-empirica-app`, such as react, simpl-schema, etc. `create-empirica-app` also generates a scaffold for starting development, so it is highly recommended to us it.

I am closing this issue, as everything works as expected with `create-empirica-app`, and manual installation is possible, but does require extra dependencies. ⛵️
