### ISSUE TITLE
Disable focus on first field in instruction steps

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#59]
InstuctionSteps have an explicit function that focus on the first field. I don't know the rationale behdind this decision, but to me this seems a bad decision. In our case, it kept forcing the page to load on the first input field which  is below a ton of text and instructions. If the screen is small, subjects will miss the instruction text above the input field and might get confused.

**Comment by npaton** [comment]
Fixed in latest version: `meteor update empirica:core`.
