### ISSUE TITLE
Add lobby component override support

### ISSUE THREAD

**Issue by npaton** [empiricaly/meteor-empirica-core#6]
As an experiment designer, I want to be able to customize the Lobby content and looks.

Proposed API: `Empirica.lobby(LobbyComponent)`.

**Comment by joshua-a-becker** [comment]
this product already is great, it's going to be so amazing with all these updates.

**Comment by npaton** [comment]
This feature was added as of v0.0.8.

**Comment by npaton** [comment]
The API is `Empirica.lobby(LobbyComponent)`, the LobbyComponent receives gameLobby, treatment and player props. Documentation coming soon.
