### ISSUE TITLE
Performance issues on 0.6.0

### ISSUE THREAD

**Issue by alexhustler** [empiricaly/meteor-empirica-core#62]
**Version:** 0.6.0

**Issue:**
When using Empirica core 0.6.0 I've noticed the game can become very slow for the players. Some rounds and stages are slow to load in the browser and the slider can be unresponsive. This causes gaps in the data as users don't have enough time to answer the question. Is this a known issue?

**Reproduce:**
The slowness is happening in production and when I test locally. I've noticed when the game has less than 10 rounds it is very fast. But when the game has more than 100 rounds it is very slow.

Our production games have 10 players plus one bot.

**Comment by npaton** [comment]
I pushed an update that _should_ fix the performance issue. `meteor update empirica:core`

Note that it is a breaking change!

Empirica used to load all rounds and stages in the browser, which would allow to have logic in the browser looking at rounds/stages other than the current one, which was convenient, if naive. This was fine with 50 rounds/stages, but once you start having 100s of rounds/stages per game, things slow down dramatically. From what I know, nobody was using this property of the browser data loading. We might be able to still enable this behavior with API changes, but nothing has been done for that yet. Previous and future rounds/stages are still accessible in the server callbacks.

Please reopen if you are still seeing performance issues. ⛵️
