### ISSUE TITLE
Game data not exported with csv/json

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/meteor-empirica-core#63]
Game data is not exported properly

## Expected Behavior
When data is set for games using 
```javascript
game.set("name1", "value1")
game.set("name2", "value2")
```
it should be exported in the data dump to the `games.csv` or `games.json` file. 

## Current Behavior
When exporting to `.csv`, the column names `data.name1`, `data.name2` appear, but they are empty.

When exporting to `.json`, the values are missing entirely.

## Steps to Reproduce (for bugs)
```javascript
Empirica.gameInit((game, treatment, players) => {
  game.set("name1", 200)
  ...
}
```
export through admin interface.

## Context
It simplifies postprocessing to have aspects unique to the game associated with the game object.

## Your Environment
Node v11.10.0
METEOR@1.8.0.2
macOS 10.13.6

**Comment by npaton** [comment]
This should be fixed. You can run `meteor update empirica:core`. 

Please reopen if you are still seeing the issue. ⛵️

**Comment by JamesPHoughton** [comment]
Thanks!
