### ISSUE TITLE
Missing bot flag?

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#65]
it seem that in the latest update we removed `p.bot`?

For example:

```
  game.players.forEach(player => {
    console.log("bot?", player.bot);
  });
```
will always output `bot? undefined` even when the player is a bot indeed.

**Comment by npaton** [comment]
I could not reproduce the issue on the server, the bot field is always equal to the name of the bot used. On the client, the `bot` field was not always published, it will now always be published starting with Empirica v0.15.0.

I also added a check to make sure bots were defined. If no bots were defined, it could create a bot without a bot field. The error does not block the batch creation, but does throw a clear error in the console. Ideally it would block the batch creation, but that is not a simple change at this point.

Let me know if these changes solve your issue. ⛵️

**Comment by npaton** [comment]
Actually, it went out as v1.0.0 because of a manipulation error on my part, and Meteor does not support unpublishing a release... Oh well.

**Comment by amaatouq** [comment]
Actually, I am doing this inside a callback: onStageStart(.)

However, I am not importing the bot component in main.js on the server and also commented out the entire bot.js code .. All I need is to set a value onStageStart()

I’ll investigate more and close the issue afterwards.

**Comment by npaton** [comment]
You must define at least one bot for bots to work in the current system. And you cannot set the bot field manually.

**Comment by amaatouq** [comment]
Got it
