### ISSUE TITLE
playerIdKey in settings creates inconsistent behavior for "new player" button

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#7]
`Meteor.settings.public.playerIdParam` sets the playerIdKey that is looked for when creating a user enters the platform, but does not impact the behavior of the "New Player" button, and users are still asked to enter a player ID.  This param also is not used in IdentifiedContainer.jsx which means that when manually entering a new player with a URL, the user is logged in as whatever their previous player in the browser was.

**Comment by joshua-a-becker** [comment]
this should be fixed so that *either* the playerIdKey param in settings is ignored in dev mode, *or* the param impacts all uses of the playerIdKey, to produce predictable behavior for the experimenter.   

i'm submitting a pull request for the latter solution---implement the param throughout.  

i don't know how to test things on core now---this was tested on the deprecated version.

**Comment by npaton** [comment]
Hey @joshua-a-becker. I'm not sure the "New Player" debugging tool for development should be mixed up with the `playerIdParam` option. The `playerIdKey` is NOT the same thing as the playerId, it is a key used to lookup the player ID in the browser cache, it is not the playerId itself, so it should not be used along with playerIdParam to automatically log in players.

I can see how automatically logging in players when clicking "New Player" might be helpful though. But we do not need playerIdParam to do that, and it might not be something we want to happen systematically, as we might want control over the playerId we use in the new window. Maybe we could have an option in the config to automatically log in the player with a random ID when we use the "New Player" config. What do you guys think ?

CC @amaatouq

**Comment by joshua-a-becker** [comment]
ok i think i see the issue--when i override this, i expose myself to the possibility that people will play more than one user in their browser, perhaps if they have two MTurk ID's.  at present, in production mode, it's not possible to do that since there is only a single cache key for playerIdParam.  what i was calling a bug, you're calling a feature.

i actually really _like_ being able to play more than one user in a browser---i tout it as a feature when i'm demo-ing games to my colleagues.  (couldn't do that at my last school.)   i _always_ demo & test multiplayer in production so this is a necessary feature to me.

BUT i have also implemented some basic security  to prevent people from 'double dipping':  the URL contains a hashed passkey that prevents playesr from making a new URL to access the game.  i had discussed this with @amaatouq over email, i'd be happy to help implement that, it's a pretty straightforward bit added to identifiedcontainer.  my current version has a 'password' that changes from session to session, but that could be replaced with the date for an easy rolling passkey:  it hashes the playerId with the password (date) to create a difficult-to-replicate URL.  i'm no hacker but i'm sure the average turker would never figure it out.  i certainly wouldn't be able to.

**Comment by joshua-a-becker** [comment]
but 

> I'm not sure the "New Player" debugging tool for development should be mixed up with the playerIdParam option. 

right now, it is:  changing the playerIdParam changes the behavior of this button.

**Comment by joshua-a-becker** [comment]
OK i have realized my confusion stems from the fact that (i thought i once saw) an example settings.json where playerIdParam=playerIdKey

so i now realize i'm asking for a totally new feature:  have the 'add new player' button pass in the playerIdParam so that you don't have to enter one.  just a shortcut for experimenters, really not that important.

**Comment by npaton** [comment]
An automated random playerId could be a useful feature to speed up testing/debugging. Feel free to add a ticket at some point. ;)

For the signed URL type feature, I can clearly see the use for it, but it's a pretty advanced feature, since there needs to be some sort of secret hashing or signing happing on the system sending players over, which I'm not sure would be possible out of the box with MTurk for example. If we do make such a system, it should be relatively easy for people to use, and not limited to one system. Anyway, it's something to think about, and again, feel free to add ticket to track the idea. ;)

**Comment by joshua-a-becker** [comment]
i use a simple javascript hash that's quite easy to implement in MTurk via copy-and-paste (the same way you might add the Turk ID to the URL to pass into playerIdParam)
