### ISSUE TITLE
Ping idle participants

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#71]
add an option when submitting the batch whether to notify `idle` participants about their state (maybe a message or a sound; or both). This will potentially deter some participants from doing other things while taking part in the experiment.

**Comment by npaton** [comment]
This might be hard to get absolutely right. First we need to reliably detect idleness. Then there might be experiments that have long phases of observing with no interactions. So we need to make the delay configurable, or dependent on factors, and stages.

This could probably be implemented outside the core, in an NPM package. Without being part of the core, we still have access to the stage/round state and the treatment, and we can try to detect player idleness from user inputs on the page. 👍

**Comment by npaton** [comment]
This is probably not something we will be adding to core. We do have idle information on the player already, so it is something that can be added outside of core. Closing (I will add open an account on a feature tracking service so we can track these kind of requests, it still might be something we want to add as a package, but not in core).

**Comment by npaton** [comment]
Added to: https://empirica.getcadet.com/feature-requests/posts/ping-idle-participants
