### ISSUE TITLE
Chat in the lobby

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#72]
It is a big problem now in online experiments that participants don't believe they are playing with other real people. In the lobby configuration, let's add `enableChat` where participants can chat with each other during their time in the lobby.

**Comment by npaton** [comment]
This is already possible manually through a custom Lobby component. Simply `Empirica.lobby(MyCustomLobby)`, and add the chat in there. I'd rather not add more magic factors. We could offer a LobbyWithChat as an npm package though.

**Comment by amaatouq** [comment]
Yes, but this is going to be a common usage for MTurk from now on. So it should be pretty easy to integrate and find by empirica users.

**Comment by npaton** [comment]
@hubertusputu1 For this, lets extract the current chat from [here](https://github.com/amaatouq/room-assignment-legacy/blob/5510eb2ae5b3914adde640cebb0154abab7dc958/imports/experiment/client/game/ChatLog.jsx) and make it into an npm package on the model of https://github.com/empiricaly/random-dot-kinematogram, which is an npm package under the `@empirica/` namespace (will give you access).
Lets make sure we have some simple CSS that will attach the chat view to the window (bottom right, see how it looks in that experiment, room-assignment-legacy).
And lets also export a LobbyWithChat from the package that will be a copy of the current core lobby + the chat in there.
