### ISSUE TITLE
`player.exit()` crashes app with error: "TypeError: Cannot read property 'id' of null"

### ISSUE THREAD

**Issue by robwayne** [empiricaly/meteor-empirica-core#73]
Trying to call `player.exit('with reason')` to exit the game prematurely fails with error: "TypeError: Cannot read property 'id' of null". Calling `player.exit('with reason')` inside the `onRoundEnd()` callback crashes the app. 
## Expected Behavior

Calling player.exit('with reason') should bring the player to the exit steps screen. 

## Current Behavior

Crashes the app with error: 
```
Cannot read property 'id' of null
I20191123-07:18:56.838(-5)?     at Object.playerIdForConn (packages/empirica:core/startup/server/connections.js:18:27)
I20191123-07:18:56.838(-5)?     at MethodInvocation.run (packages/empirica:core/api/players/methods.js:386:33)
I20191123-07:18:56.838(-5)?     at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:94:12)
I20191123-07:18:56.838(-5)?     at MethodInvocation.Players.methods.admin.earlyExitPlayer (packages/mdg:validated-method/validated-method.js:57:23)
I20191123-07:18:56.839(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20191123-07:18:56.839(-5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1689:15)
I20191123-07:18:56.839(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20191123-07:18:56.839(-5)?     at resolve (packages/ddp-server/livedata_server.js:1687:36)
I20191123-07:18:56.839(-5)?     at new Promise (<anonymous>)
I20191123-07:18:56.839(-5)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
I20191123-07:18:56.840(-5)?     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
I20191123-07:18:56.840(-5)?     at ValidatedMethod.call (packages/mdg:validated-method/validated-method.js:70:30)
I20191123-07:18:56.840(-5)?     at Object.player.exit.reason [as exit] (packages/empirica:core/api/player-stages/augment.js:81:21)
I20191123-07:18:56.840(-5)?     at players.forEach.player (server/callbacks.js:78:14)
I20191123-07:18:56.840(-5)?     at Array.forEach (<anonymous>)
I20191123-07:18:56.840(-5)?     at Empirica.onRoundEnd (server/callbacks.js:70:11)
I20191123-07:18:56.841(-5)?  => awaited here:
I20191123-07:18:56.841(-5)?     at Promise.await (/Users/robudhabi/.meteor/packages/promise/.0.11.2.1ixw4hn.8uhlk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20191123-07:18:56.841(-5)?     at Server.apply (packages/ddp-server/livedata_server.js:1638:14)
I20191123-07:18:56.841(-5)?     at ValidatedMethod.call (packages/mdg:validated-method/validated-method.js:70:30)
I20191123-07:18:56.841(-5)?     at Object.player.exit.reason [as exit] (packages/empirica:core/api/player-stages/augment.js:81:21)
I20191123-07:18:56.841(-5)?     at players.forEach.player (server/callbacks.js:78:14)
I20191123-07:18:56.841(-5)?     at Array.forEach (<anonymous>)
I20191123-07:18:56.842(-5)?     at Empirica.onRoundEnd (server/callbacks.js:70:11)
I20191123-07:18:56.842(-5)?     at endOfStage (packages/empirica:core/api/stages/finish.js:43:5)
I20191123-07:18:56.842(-5)?     at Games.find.forEach.game (packages/empirica:core/api/games/server/cron.js:33:9)
I20191123-07:18:56.842(-5)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
I20191123-07:18:56.842(-5)?     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)
I20191123-07:18:56.842(-5)?     at Object.task (packages/empirica:core/api/games/server/cron.js:25:23)
I20191123-07:18:56.843(-5)?     at run (packages/empirica:core/startup/server/cron.js:53:14)
I20191123-07:18:56.843(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20191123-07:18:56.843(-5)?     at packages/meteor.js:550:25
I20191123-07:18:56.843(-5)?     at runWithEnvironment (packages/meteor.js:1286:24)

```

## Steps to Reproduce (for bugs)

1. Inside `onRoundEnd` callback iterate through each player object. 
2. Call `player.exit('with reason')` or simply call `players[0].exit('with reason')` 

## Context

We are trying to stop the current game and bring the user to exitSteps if they have been inactive throughout multiple rounds or another participant in their treatment drops out (is also inactive / closes the experiment). 

## Your Environment

- Version used: 1.3.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Mac OS 10.15 Catalina
- Link to your project:

**Comment by npaton** [comment]
I pushed a fix, please update (`meteor update empirica:core`) and let me know if you are still having problems. ⛵️

**Comment by robwayne** [comment]
Thanks for the quick update! 

However `meteor update empirica:core` also does not work.  Running this returns with error: 
```
While checking for empirica:core@1.3.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

Additionally, calling `player.exit('with reason')` inside any client Component e.g. `Round.jsx` (outside `callback.js`) works without error, however even if the only player in the game exits (is brought to the ExitSteps screen), the game continues in the background indefinitely until all rounds are finished. Therefore, it seems the error that was mentioned in the original issue post only occurs when `player.exit()` is called inside the `callback.js` file. Therefore, if the only player in the game has been sent to exit, shouldnt the game stop? More importantly a method such as `Empirica.endGame()` would be really handy to stop the game in any case. Thanks!

**Comment by npaton** [comment]
Sorry for the update issue, there was apparently a glitch when I uploaded the last version. Please try to update again (`meteor update empirica:core`).

Yes, indeed, the game should end, and it does not, it's currently a known issue. We decided to give the capability to exit players early, even if we don't have the mechanism to stop the game when all players have exited. It should not break things overall, but it is not the expected behavior. We intend to address this in a future update. The end game function is a good idea, and we will add it when we fix the empty game ending. Maybe something like `game.end()`.

**Comment by robwayne** [comment]
Thanks for your reply! Upgrading empirica:core now works (although after a few tries). Also would love to be kept in the loop for the fix to `player.exit()` and introduction of `game.end()`.

**Comment by robwayne** [comment]
Also, how long would you estimate the intended behavior fix to take? I assume you have other priorities as well so this is in no way an urge to rush! Our team would love to have the experiment out on Empirica within the next two weeks and it would be great to  have this feature in place if it can be! We currently have a bit of a "hacky" way of  getting around the current behavior. This poses problems for us, however, because although the game has *technically* ended, participants might be able to re-enter the game at a later point or new participants being assigned to this now invalid game. Thanks for your time and understanding.

**Comment by npaton** [comment]
I see. New players shouldn't be able to be assigned to an ongoing game. And players coming back with the same Player ID should be lead back to the exit. That said, I am not sure your exact scenario, and there are probably edge cases for this.

We will probably not be able to change this within the next couple of weeks unfortunately. I am on a semi-vacation at the moment. 🏖 We do also have a large body of work on assignment going on right now, that  will probably take priority for the next few weeks.

I might be able to help with the specific behavior you are seeing, as I don't think you should see new players assigned to the old game, nor should exited players be able to play again.

I am going to close this issue. If you want to get news on any progress with the 2 new improvements we talked about here, please follow https://github.com/empiricaly/meteor-empirica-core/issues/74 and https://github.com/empiricaly/meteor-empirica-core/issues/75. ⛵️
