### ISSUE TITLE
Add `game.end()` method to allow to end the game early

### ISSUE THREAD

**Issue by npaton** [empiricaly/meteor-empirica-core#75]
The game designer should be able to end the game cleanly at any point. Should save timestamp of when the game ended and maybe a different state than just "finished"

Question: Should we add a status message? As a note for the designer as to why the game ended early. Not sure it's useful as we can always set custom values like `game.set("myreasonforending", "noreason...")`, but it would make it like more like `player.exit("good reason here")`. Maybe the status message can help the state finished to be characterized, instead of adding a new state.

**Comment by robwayne** [comment]
Hi @npaton, you mentioned you could  possibly be able to help with the problem we were having. Would it be possible to communicate over email? Additionally, we have a question: is it possible to dynamically add rounds while the game is playing? Thanks!

**Comment by npaton** [comment]
It is currently not possible to add rounds while the game is playing. Another feature we do want to add. The workaround we've recommended is to create as many rounds as you will need at the maximum, and then exit players early when the time is right. It's not ideal and has the same issue of the game not ending when everyone exits, but it can sometimes help get around the current limitation.

You can find my email address on my Github profile page, feel free to send me an email. 👍
