### ISSUE TITLE
A Link is missing from the tutorial 

### ISSUE THREAD

**Issue by Shamma009** [empiricaly/meteor-empirica-core#83]
## Expected Behavior
 There is a missing link which  shows how to open multiple players in one browser. It is in bold below 

Go to http://localhost:3000/ and enjoy! If you don't have 3 friends to play with you, you always can use the new player button in development (f**or more details see this**), which can add an arbitrary number players to the experiment while staying in the same browser (i.e., no need to open different browsers). 

This is missing in the three tutorials: 

1.  https://empirica.ly/docs/random-dot-motion
2. https://empirica.ly/docs/guess-the-correlation
3. https://empirica.ly/docs/room-assignment

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by hubertusputu1** [comment]
Hi @Shamma009 , my name is Hubertus, i am here working with @npaton and looking into this problem. The docs was updated, you can check on this https://docs.empirica.ly . We will link the new docs to the current link soon. Thank You.
