### ISSUE TITLE
Game starts slow for games with many rounds / stages

### ISSUE THREAD

**Issue by LBrinkmann** [empiricaly/meteor-empirica-core#90]
## Current Behaviour
We found the game creation being bottlenecked by the database performance for games with many rounds and/or many stages. In our setting with 80 rounds a 3 stages and an external database, game creation could take up to 40seconds. The reason seems to be a large number of individual inserts/updates during creation.

https://github.com/empiricaly/meteor-empirica-core/blob/f01ca69d3078fc8efd25129a1ac23e3f0cb34d22/api/games/create.js#L187-L235

## Possible Solution
Using bulk operations on the database.

**Comment by npaton** [comment]
That would make a lot of sense, we will be looking into that. Thank you.

**Comment by npaton** [comment]
For reference: https://mongodb.github.io/node-mongodb-native/api-generated/unordered.html

**Comment by hubertusputu1** [comment]
Hi Levin @LBrinkmann , my name is Hubertus, i am here woking together with @npaton to solve this issue. Issue is solved and the improvement will appear in the upcoming next version of Empirica. Thank You 😊
