### ISSUE TITLE
Logging Submission Timestamps

### ISSUE THREAD

**Issue by josephbb** [empiricaly/meteor-empirica-core#93]
It would be useful to have a server-side timestamp when the player presses submit. In the current version of empirica, this can be done either clientside in submit callback, or serverside in the onSubmit callback. Client-side timestamps are unreliable and out of sync with the server. Unfortunatlely, the round object passed to onSubmit server is not the player-round and accessing the player.round object does not allow calling player.round.set("SubmittedAt", new Date). 

## Expected Behavior
Ideally, it would be possible to call player.round.set("foo", bar) in the onSubmit callback. 

## Current Behavior
Currently doing so produces an error (set not defined)

## Possible Solution
Passing the player-round object would fix the issue, I believe. 

## Steps to Reproduce (for bugs)
This can be reproduced by making a call as described above.

**Comment by npaton** [comment]
It's a good idea, we will add an automatic timestamp. And we will add `player.round/stage.set/get` in onSubmit.
