### ISSUE TITLE
Lazy data fetching in game callbacks

### ISSUE THREAD

**Issue by LBrinkmann** [empiricaly/meteor-empirica-core#94]
## Suggested behavior

The game callbacks only receive the game and not the players, stages, and rounds. Instead, helpers on the game object could allow to conveniently fetch additional data when needed. 

## Current Behaviour

Prior to any callback (such as onRoundStart, onStageTick, ...) the game, the player, the stages and all rounds are fetched from the mongoDB. Unfortunately, meteor does not seem to cache these queries serverside (but only on the clients) [https://guide.meteor.com/collections.html]. 

Within these callbacks often only part of this data is actually needed (often enough the callback is not even used). This results in a large number of unnecessary database queries. As a result, we experienced slow transitions between stages #89 for games with many stages/rounds.

## Suggested Implementation

* Adding helpers (e.g. like in api/game-lobbies/game-lobbies.js) on the game to fetch, e.g.
    * player
    * rounds
    * currentRound
    * stages
    * currentStage
* pass to the callback only the game itself
* game developer than can fetch additional data, when needed

## Files

* api/games/create.js
* api/games/server.js
* api/server/onchange.js
* api/server/onsubmit.js
* api/server/finish.js

**Comment by npaton** [comment]
We do plan to not pre-load all of these in Empirica v2 (and we will probably have some amount of local caching that could be enabled). I think the most commonly used objects (player, current round and stage) do still make sense to make available immediately, as the cost is moderate and the use case common ; and we can probably hide the DB calls for the large collections behind a JS getter. So if we have the time, we will implement this in v1. But it's currently not planned, and I cannot guaranty when we'd get to it. PRs are welcome (as long as we make sure we do not break the current APIs).

But we should definitely be checking to see if all these callbacks are used before collecting all this data as it is. In the back of my mind, I thought we were checking this, but we are not indeed, that could be a big quick win. That is something I'd like us to look into very soon. PRs also welcome. :)
